### ISSUE TITLE
Codepoint builtins

### ISSUE THREAD

**Issue by jacobofbrooklyn** [Thunno/Thunno2#15]
(I'm Jacob on SE)

This seems like a very cool language and good successor to the original Thunno. I realize it still seems to be in early development but I just wanted to point out that it is missing built-ins for dealing with codepoints. 

The original Thunno was also missing these functions, which was pretty annoying at times and basically makes it not able to compete with other languages for many challenges.

Commands that would be very useful:
- number &rarr; string
- string &rarr; number[]
- number[] &rarr; string
- codepoint at index of string

I don't know much python but I might be able to submit a PR if it would help @nayakrujul

**Comment by nayakrujul** [comment]
Do you mean like `chr` and `ord` in Python (Number to Unicode and Unicode to Number). Because if you do, there is already a built-in: [`C`](https://github.com/Thunno/Thunno2/blob/main/docs/commands.md#c-chr--ord) (note: it's overloaded to be both `chr` and `ord`). Also, Thunno 1 had builtins for that as well: `C` and `O`.

**Comment by jacobofbrooklyn** [comment]
Also, it would be nice if the `B` flag converted a number array output to a string output.

**Comment by jacobofbrooklyn** [comment]
Oops, didn't see those, sorry! It still could be nice to have number[] &rarr; string though. Closing this as my mistake.
